name: Publish

on:
  push:
    branches: [master, dependabot/**]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '16'
          registry-url: https://npm.pkg.github.com
      - run: yarn install
      - run: yarn test
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}