name: Publish

on:
  push:
    branches: [master, dependabot/**]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
          registry-url: https://npm.pkg.github.com
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmAuthToken $NPM_TOKEN
          yarn config set npmAlwaysAuth true
          yarn config set npmScopes.orikami-nl.npmAuthToken $NPM_TOKEN
          yarn config set npmScopes.orikami-nl.npmAlwaysAuth true
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn
      # - run: yarn test
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}