name: Publish

on:
  push:
    branches: [master, dependabot/**]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
          registry-url: https://npm.pkg.github.com
      - run: yarn
      # - run: yarn test
      - run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}